### ISSUE TITLE
Both PFC_WD_DB and CONFIG_DB use db 4

### ISSUE THREAD

**Issue by JipanYanga** [Azure/sonic-swss-common#125]
Is this the intended design?

schema.h:
    9  #define LOGLEVEL_DB     3
   10: #define PFC_WD_DB       4

database.json
   23:       "CONFIG_DB": {
   24          "db": 4
   25        }

configdb-load.sh
16: echo -en "SELECT 4\nSET CONFIG_DB_INITIALIZED true" | redis-cli

**Comment by marian-pritsak** [comment]
Why isn't CONFIG_DB declared in the schema?
