### ISSUE TITLE
After we call RedisReply::release(),function RedisReply::~RedisReply() may generate a core  in redis version 3.2.11 

### ISSUE THREAD

**Issue by Chen0Yang** [Azure/sonic-swss-common#170]
In function RedisReply::release(), we set m_reply = NULL; 
In function RedisReply::~RedisReply(), we call freeReplyObject(m_reply) directly with out any judgement.

In redis ,before Wed Dec 21 12:11:56 2016, function void freeReplyObject(void *reply) will directly access r->type without any judgement. There will generate a core when reply is NULL.

I have check function void freeReplyObject(void *reply) in redis version 3.2.11,it will generate a core if reply is NULL. While redis version 4.0.6 will not generate any core.

**Comment by lguohan** [comment]
@qilimsft to look

**Comment by lguohan** [comment]
we are using 3.2.4 now in sonic. We haven't tested on 3.2.11. what is the concern here?

**Comment by Chen0Yang** [comment]
@lguohan I don't have redis version 3.2.4 source code, you can check function freeReplyObject in file deps/hiredis/hiredis.c with redis version 3.2.4, is there any judgement before use reply. 
redis version 4.0.6 will return directly if reply is NULL.

**Comment by qiluo-msft** [comment]
We are using debian repo's hiredis (https://github.com/Azure/sonic-buildimage/blob/master/src/hiredis/Makefile), no redis source code at all. Checking the code there, there should be no 'free NULL' problem.
