### ISSUE TITLE
Continuous ProducerStateTable del/set call may leave stale FV in table data

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-swss-common#236]
One scenario:

Existing table data  --   `Key1 :  f1/v1, f2/v2`

Two produceStateTable operation on key1, del then set,
```
del --- key1

set --- key1: f1/v1, f3/v3
```
producerStateTable uses SADD to store key1,   del and set may be combined if consumerState is not quick enough to pickup del before set.   what is left in redis DB will be:
 
`key1: f1/v1,  f2/v2,  f3/v3`

While the correct one should be `key1: f1/v1, f3/v3`

The merge of of del and set may trigger other unexpected behavior for the user of consumerState.

**Comment by lguohan** [comment]
@jipanyang , is this design issue or not? can you triage it?

**Comment by nikos-github** [comment]
@lguohan @jipanyang Jipan explained to me under what circumstances this problem will occur and that right now since the prefix's set is fixed (field set for key prefix doesn’t change), it can not happen.

**Comment by jipanyang** [comment]
Right, for route BGP provide two fields "nexthop" and "ifname", for neighbor, they are "family" and "neigh",  new FV will overwrite old FV. 

Possibly problem could happen with those applications in cfgMgr which may have variable number of fields for each set via ProducerStateTable.

**Comment by jipanyang** [comment]
Fixed.
