### ISSUE TITLE
message queue in producertable/consumertable has lots of immediate states

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss-common#42]
during ecmp route convergence period, a route will be added to message queue due to the nhg changes, e.g,

```
    10.0.0.1/24 -> 1.1.1.1,2.2.2.2
    10.0.0.1/24 -> 1.1.1.1,2.2.2.2,3.3.3.3
    10.0.0.1/24 -> 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4

```

all these messages should be consolidated into one message so that swss does not have to put immediate states onto asic.

current message queue does not consolidating messages with a same key. The idea is to use sets instead of list to hold the message queue. 

The producer set(key, field, value) will put the state into the app db, meanwhile put the key into the set using SADD. del(key) will remove the key from the db, meanwhile put the key into the set.

The consumer will use the SPOP to read from the set, and hgetall to get all the field and value for the key. the SPOP and HGETALL must to atomic operation. So, we need to lua to achieve this.

pop.lua

```
local key = redis.call("SPOP", KEYS[1])
if not key then return end
local key2 = redis.call("HGETALL", key)
return {key, key2}
```

We also need to upgrade redis to 3.2.4.

**Comment by qiluo-msft** [comment]
Implemented in https://github.com/Azure/sonic-swss-common/pull/55
