### ISSUE TITLE
There is a problem that hostcfgd blocks forever and does not react to SIGTERM causing a delay in warm boot.

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-swss-common#603]
There is a problem that hostcfgd blocks forever and does not react to SIGTERM causing a delay in warm boot.
When hitting this line  https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-host-services/scripts/hostcfgd#L1241 .

Example:

```
>>> from swsscommon import swsscommon
>>> c=swsscommon.ConfigDBConnector()
>>> c.subscribe('A', lambda a: None)
>>> c.connect()
>>> c.listen()


^C^C^C^C
```
@qiluo-msft This looks like a swss-common issue.

This wasn't seen for some reason during 500 warm boot tests on 202012 since warm reboot is executed early enough before hostcfgd stucks in a listen().

_Originally posted by @stepanblyschak in https://github.com/Azure/sonic-buildimage/issues/10510#issuecomment-1100055929_

**Comment by liuh-80** [comment]
ACK, will start investigation this issue.

**Comment by liuh-80** [comment]
I found there are 2 place have infinite loop issue:

[std::map<std::string, std::string> PubSub::listen_message()](https://github.com/Azure/sonic-swss-common/blob/15c0f729648ee9f26ac9aea767d5712db34ca298/common/pubsub.cpp#L135)

https://github.com/Azure/sonic-swss-common/blob/36e1f61691df7aa44782a377e4082cc4380f1018/common/configdb.h#L97

We need exit these infinite loop when receive SIGTERM by add a SIGTERM handler and check SIGTERM  status in loop. also we may need check if other signal also need handle, for example SIGKILL

**Comment by liat-grozovik** [comment]
@qiluo-msft any reason the issue is not opened on buildimage for tracking? i believe we only track it and not submodules.

**Comment by liuh-80** [comment]
To minimize code change and make code scalable, my proposal is:
1.Add a CancellationToken class.
2.And add new parameter to these existed API.
3.Code change in hostcfgd to use the new API with a signal handler.

**Comment by liuh-80** [comment]
Here is a draft PR for this issue:

https://github.com/Azure/sonic-swss-common/pull/606

>>> from swsscommon import swsscommon
>>>
>>> global_cancellation_token = swsscommon.SignalHandlerHelper.GetCancellationToken(2)
>>> swsscommon.SignalHandlerHelper.RegisterSignalHandler(2)
>>>
>>> c=swsscommon.ConfigDBConnector()
>>> c.subscribe('A', lambda a: None)
>>> c.connect()
>>> c.listen(global_cancellation_token, None)
^C>>>

**Comment by liuh-80** [comment]
Update: here is latest example:


>>> from swsscommon import swsscommon
>>>
>>>
>>> global_cancellation_token = swsscommon.CancellationToken()
>>>
>>> swsscommon.SignalHandlerHelper.RegisterCancellationToken(2, global_cancellation_token)
>>> swsscommon.SignalHandlerHelper.RegisterSignalHandler(2)
>>>
>>> c=swsscommon.ConfigDBConnector()
>>> c.subscribe('A', lambda a: None)
>>> c.connect()
>>> c.listen(global_cancellation_token, None)

^C>>>

**Comment by qiluo-msft** [comment]
> @qiluo-msft any reason the issue is not opened on buildimage for tracking? i believe we only track it and not submodules.

If it is obvious issue in submodule, we will move it to submodule's repo.

**Comment by liat-grozovik** [comment]
@liuh-80, @qiluo-msft as this one is blocking https://github.com/Azure/sonic-buildimage/pull/10510. can you please see how we can expedite the solution and the review?
