### ISSUE TITLE
parseMacString() has issues

### ISSUE THREAD

**Issue by pavel-shirshov** [Azure/sonic-swss-common#91]
parseMacString() considers 52:54:00:25::E9 and 52:54:00:25:E9 as good mac addresses

**Comment by kcudnik** [comment]
Solled in #92

**Comment by pavel-shirshov** [comment]
It wasn't. It's a separate issue.

**Comment by pavel-shirshov** [comment]
Fixed by https://github.com/Azure/sonic-swss-common/pull/171
